version: '3'

services:
  database:
    restart: always
    image: 'postgres:latest'
    ports:
      - 5432:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USERNAME=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database

  api:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app:delegated
      - /usr/src/app/node_modules/
    ports:
      - 8000:80
    env_file: .env